#!/bin/bash
set -e

ADMIN_USER="$(< /run/secrets/ADMIN_USER)"
ADMIN_PASS="$(< /run/secrets/ADMIN_PASS)"

DATABASE="$(< /run/secrets/DB_NAME)"
USER="$(< /run/secrets/DB_USER)"
PASSW="$(< /run/secrets/DB_PASS)"

PGPASSWORD="$ADMIN_PASS" psql -v ON_ERROR_STOP=1 --username "$ADMIN_USER" <<-EOSQL
	CREATE DATABASE ${DATABASE};

	CREATE USER ${USER} WITH ENCRYPTED PASSWORD '${PASSW}';

	REVOKE ALL ON DATABASE ${DATABASE} FROM PUBLIC;
	GRANT CONNECT ON DATABASE ${DATABASE} TO ${USER};
	GRANT CONNECT ON DATABASE ${DATABASE} TO readonly;
EOSQL

PGPASSWORD="$ADMIN_PASS" psql -v ON_ERROR_STOP=1 --username "$ADMIN_USER" "${DATABASE}" <<-EOSQL
	REVOKE ALL ON SCHEMA public FROM PUBLIC;
	GRANT USAGE ON SCHEMA public TO readonly;
	GRANT USAGE ON SCHEMA public TO ${USER};

	ALTER DEFAULT PRIVILEGES IN SCHEMA public
		GRANT SELECT ON TABLES TO readonly;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public
		GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${USER};
EOSQL
