#!/bin/bash
set -e

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE readonly;
  ALTER DEFAULT PRIVILEGES FOR ROLE client IN SCHEMA public
    GRANT SELECT ON TABLES TO readonly;
EOSQL
