#!/bin/bash
set -e

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  ALTER DEFAULT PRIVILEGES IN SCHEMA public
	  REVOKE ALL ON TABLES FROM PUBLIC;
EOSQL
