#!/bin/bash
set -e
DATABASE=tagger
USER=tag
PASSW=tagbot

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE ${DATABASE};
	CREATE USER ${USER} WITH ENCRYPTED PASSWORD '${PASSW}';
	GRANT ALL PRIVILEGES ON DATABASE ${DATABASE} TO ${USER};
	REVOKE ALL ON DATABASE ${DATABASE} FROM PUBLIC;
	GRANT CONNECT ON DATABASE ${DATABASE} TO readonly;
EOSQL
