#!/bin/bash
set -e

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE tagger;
	CREATE USER tag WITH ENCRYPTED PASSWORD 'tagbot';
	GRANT ALL PRIVILEGES ON DATABASE tagger TO tag;
EOSQL
