#!/bin/bash
set -e

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE DATABASE eli_bot;
	CREATE USER eli WITH ENCRYPTED PASSWORD 'elibot';
	GRANT ALL PRIVILEGES ON DATABASE eli_bot TO eli;
EOSQL
