#!/bin/bash
set -e

if [ -z ${BOT_DATABASE_USER} ]; then
  USER="${BOT_DATABASE_USER}"
else
  USER="$(< /run/secrets/BOT_DATABASE_USER)"
fi

if [ -z ${BOT_DATABASE_PASS} ]; then
  PASSW="${BOT_DATABASE_PASS}"
else
  PASSW="$(< /run/secrets/BOT_DATABASE_PASS)"
fi

READONLY=$READONLY_ROLE

PGPASSWORD="$POSTGRES_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE IF NOT EXISTS $READONLY

  CREATE USER IF NOT EXISTS $USER WITH ENCRYPTED PASSWORD '$PASSW';
    GRANT $READONLY TO $USER
EOSQL
